export const users = [
  {
    _id: 1,
    username: "john_doe",
    email: "john.doe@example.com",
    firstName: "John",
    lastName: "Doe",
  },
  {
    _id: 2,
    username: "jane_smith",
    email: "jane.smith@example.com",
    firstName: "Jane",
    lastName: "Smith",
  },
  {
    _id: 3,
    username: "charlie_brown",
    email: "charlie.brown@example.com",
    firstName: "Charlie",
    lastName: "Brown",
  },
  {
    _id: 4,
    username: "alice_jones",
    email: "alice.jones@example.com",
    firstName: "Alice",
    lastName: "Jones",
  },
  {
    _id: 5,
    username: "bob_miller",
    email: "bob.miller@example.com",
    firstName: "Bob",
    lastName: "Miller",
  },
  {
    _id: 6,
    username: "carol_davis",
    email: "carol.davis@example.com",
    firstName: "Carol",
    lastName: "Davis",
  },
  {
    _id: 7,
    username: "dave_clark",
    email: "dave.clark@example.com",
    firstName: "Dave",
    lastName: "Clark",
  },
  {
    _id: 8,
    username: "emma_wilson",
    email: "emma.wilson@example.com",
    firstName: "Emma",
    lastName: "Wilson",
  },
  {
    _id: 9,
    username: "frank_hall",
    email: "frank.hall@example.com",
    firstName: "Frank",
    lastName: "Hall",
  },
  {
    _id: 10,
    username: "grace_lee",
    email: "grace.lee@example.com",
    firstName: "Grace",
    lastName: "Lee",
  },
];
